# Generated by Django 5.1.1 on 2024-09-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioDeAbertura', models.TimeField()),
                ('horarioDeFechamento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDaMesa', models.CharField(max_length=100)),
                ('capacidadeDaMesa', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('capacidadeDeMesas', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='dataDaReserva',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='hora',
            new_name='horaDaReserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_de_pessoas',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.mesa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.restaurantes'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.restaurantes'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.usuarios'),
        ),
    ]
